package com.rentingframework.core.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
 
/**
 * A unit of work inside a Group. Completing a Task is the fixed trigger
 * for gamification (core's RewardPolicy hook fires here) — but how a
 * Task comes to exist varies a lot per app:
 *   - Housing: created manually by a resident (chore).
 *   - Carpooling: auto-generated when a booking ends (refuel, mileage log).
 *   - Expert: derived from a completed session (deliverable/note).
 * That creation logic lives in each app's TaskService, not here.
 *
 *   @Entity
 *   @Table(name = "carpooling_tasks")
 *   public class CarpoolingTask extends Task {
 *       private boolean autoGenerated;
 *   }
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "tasks")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Task {
 
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
 
    @Column(nullable = false)
    private String description;
 
    @Column(nullable = false)
    private boolean completed = false;
 
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "group_id", nullable = false)
    private Group group;
 
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_user_id")
    private User assignedUser;
}