package com.rentingframework.core.service;
 
import com.rentingframework.core.dto.TaskResponseDTO;
import com.rentingframework.core.exception.ResourceNotFoundException;
import com.rentingframework.core.model.Group;
import com.rentingframework.core.model.Task;
import com.rentingframework.core.model.User;
import com.rentingframework.core.repository.TaskRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
 
import java.util.List;
 
@Service
@RequiredArgsConstructor
public class TaskService {
 
    private final TaskRepository taskRepository;
    private final GroupService groupService;
    private final UserService userService;
    
    // O Spring exigirá que a aplicação consumidora proveja esse Bean!
    private final RewardPolicy rewardPolicy;
 
    /**
     * Adiciona uma nova tarefa ao grupo.
     * A aplicação pode mandar uma entidade Task ou uma subclasse (ex: CarpoolingTask).
     */
    @Transactional
    public Task addTask(Task task, Long groupId, Long assignedUserId) {
        // groupId is the Group's own ID, not the Listing's — use
        // getGroupById here, never getOrCreateGroupForListing.
        Group group = groupService.getGroupById(groupId);
 
        task.setGroup(group);
 
        if (assignedUserId != null) {
            User assignee = userService.findById(assignedUserId);
            task.setAssignedUser(assignee);
        }
 
        return taskRepository.save(task);
    }
 
    @Transactional(readOnly = true)
    public List<Task> listByGroup(Long groupId) {
        return taskRepository.findByGroupId(groupId);
    }
 
    /**
     * O Método Chave: Altera o status e dispara a gamificação obrigatoriamente.
     *
     * actingUserId é quem está clicando o toggle agora — não necessariamente
     * quem a task já tinha como assignedUser. Isso preserva o comportamento
     * original do CampusHome: qualquer membro do grupo pode "reivindicar"
     * uma tarefa completando-a, e o RewardPolicy dispara sempre, para quem
     * agiu, e não apenas quando a task já vinha pré-atribuída.
     */
    @Transactional
    public Task toggleStatus(Long taskId, Long actingUserId) {
        Task task = taskRepository.findById(taskId)
                .orElseThrow(() -> new ResourceNotFoundException("Tarefa não encontrada."));
        User actingUser = userService.findById(actingUserId);
 
        boolean newStatus = !task.isCompleted();
        task.setCompleted(newStatus);
 
        if (newStatus) {
            task.setAssignedUser(actingUser);
        }
 
        Task saved = taskRepository.save(task);
 
        // Aciona o hook de gamificação (Fixed Point) — sempre, para quem agiu.
        rewardPolicy.onTaskToggled(actingUser, saved, newStatus);
 
        return saved;
    }
 
    @Transactional
    public void deleteTask(Long taskId) {
        if (!taskRepository.existsById(taskId)) {
            throw new ResourceNotFoundException("Tarefa não encontrada.");
        }
        taskRepository.deleteById(taskId);
    }
 
    /**
     * Conversão base para apps cuja subclasse de Task não adiciona campos
     * extras. Se ela adicionar (ex: CarpoolingTask.autoGenerated), o app
     * monta seu próprio DTO chamando os getters direto, em vez de usar
     * este método.
     */
    public TaskResponseDTO toResponseDto(Task task) {
        return new TaskResponseDTO(task.getId(), task.getDescription(), task.isCompleted());
    }
}